# Set the basic configuration of the task to be performed
env {
  parallelism = 1
  job.mode = "BATCH"
  checkpoint.interval  = 1000
}

source {
  Clickhouse {
    host = "xxxx:8123"
    database = "db"
    username = "user"
    password = "passwd"
    server_time_zone = "UTC"
    sql = "select * from db.cc"
    batch_size = 1024
    clickhouse.config = {
      "socket_timeout": "300000"
    }
  }
}

sink {
  Clickhouse {
    host = "yyyy:8123"
    database = "dd"
    table = "cc"
    username = "user"
    password = "passwd"
  }
}
